version: "3.5"

services:
  webhookd:
    hostname: webhookd
    image: ncarlier/webhookd:latest
    container_name: webhookd
    restart: always
    ports:
    - "8080:8080"
    environment:
    - WHD_SCRIPTS_DIR=/scripts
    volumes:
    - ./scripts:/scripts
